name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker-container

      - name: Set image tags
        id: meta
        run: |
          DATE_TAG=$(date +'%y%m%d')
          FULL_REPO=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          echo "main-date-tag=ghcr.io/$FULL_REPO:main-$DATE_TAG" >> $GITHUB_OUTPUT
          echo "main-tag=ghcr.io/$FULL_REPO:main" >> $GITHUB_OUTPUT

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile-Plugins
          push: true
          tags: |
            ${{ steps.meta.outputs.main-date-tag }}
            ${{ steps.meta.outputs.main-tag }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
